id: kubecost
displayName: Kubecost
description: With New Relic and Kubecost, you can understand the costs associated with each of your Kubernetes resources.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/kubernetes-pixie/kubecost/get-started-kubecost/
icon: logo.png
