slug: kubecost
title: Kubecost Integration
description: |
  ## About Kubecost

  With New Relic and Kubecost, you can understand the costs associated with each of your Kubernetes resources.

  ## About the Quickstart

  With this Quickstart, you'll install the Kubecost integration and send the data to New Relic. Then, you can use the quickstart Dashboard to visualize the costs associated with your cluster.

  * What are the primary drivers of cost in my cluster (CPU, storage, egress, etc)?
  * Which node(s) is driving recent cost increases in my cluster?
  * What are the cost breakdowns by namespace for my workloads?
  * How can I tailor cost estimation based on the pricing/discounts provided to me by my cloud providers?

summary: |
  With New Relic and Kubecost, you can understand the costs associated with each of your Kubernetes resources.
level: New Relic
authors:
  - New Relic
  - Natalie Serrino
dataSourceIds:
  - kubecost
documentation:
  - name: Kubecost
    description: |
      Install and configure the Kubecost agent
    url: https://docs.newrelic.com/docs/kubernetes-pixie/kubecost/get-started-kubecost/
keywords:
  - kubecost
  - agent
  - Kubernetes
  - cost
  - OpenCost
dashboards:
  - kubecost
icon: logo.png
